sudo: required
language: python
python:
  - '3.6'
services:
  - docker

env:
  matrix:
    - OS=centos:6
    - OS=centos:7
    - OS=fedora:24
    - OS=fedora:25
    - OS=fedora:26
    - OS=fedora:27
    - OS=ubuntu:14.04
    - OS=ubuntu:16.04
    - OS=ubuntu:16.10
    - OS=ubuntu:17.04
    - OS=ubuntu:17.10
    - OS=debian:7
    - OS=debian:8
    - OS=debian:9

script:
  - python .run-docker.py ${OS}
